/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as UniverseCommerceRouteImport } from './routes/universe-commerce'
import { Route as TradingHubRouteImport } from './routes/trading-hub'
import { Route as TpsRouteImport } from './routes/tps'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as SocialClubRouteImport } from './routes/social-club'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoyalPriesthoodRouteImport } from './routes/royal-priesthood'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PropertyRouteImport } from './routes/property'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeritageJudahRouteImport } from './routes/heritage-judah'
import { Route as HeedRouteImport } from './routes/heed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as DltRouteImport } from './routes/dlt'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreatorsCalendarRouteImport } from './routes/creators-calendar'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoinRouteImport } from './routes/coin'
import { Route as BusinessNetworkRouteImport } from './routes/business-network'
import { Route as BlackCardRouteImport } from './routes/black-card'
import { Route as BankingAccountsRouteImport } from './routes/banking-accounts'
import { Route as BankingRouteImport } from './routes/banking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseCommerceRoute = UniverseCommerceRouteImport.update({
  id: '/universe-commerce',
  path: '/universe-commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingHubRoute = TradingHubRouteImport.update({
  id: '/trading-hub',
  path: '/trading-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const TpsRoute = TpsRouteImport.update({
  id: '/tps',
  path: '/tps',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialClubRoute = SocialClubRouteImport.update({
  id: '/social-club',
  path: '/social-club',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoyalPriesthoodRoute = RoyalPriesthoodRouteImport.update({
  id: '/royal-priesthood',
  path: '/royal-priesthood',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyRoute = PropertyRouteImport.update({
  id: '/property',
  path: '/property',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageJudahRoute = HeritageJudahRouteImport.update({
  id: '/heritage-judah',
  path: '/heritage-judah',
  getParentRoute: () => rootRouteImport,
} as any)
const HeedRoute = HeedRouteImport.update({
  id: '/heed',
  path: '/heed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const DltRoute = DltRouteImport.update({
  id: '/dlt',
  path: '/dlt',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorsCalendarRoute = CreatorsCalendarRouteImport.update({
  id: '/creators-calendar',
  path: '/creators-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoinRoute = CoinRouteImport.update({
  id: '/coin',
  path: '/coin',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessNetworkRoute = BusinessNetworkRouteImport.update({
  id: '/business-network',
  path: '/business-network',
  getParentRoute: () => rootRouteImport,
} as any)
const BlackCardRoute = BlackCardRouteImport.update({
  id: '/black-card',
  path: '/black-card',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingAccountsRoute = BankingAccountsRouteImport.update({
  id: '/banking-accounts',
  path: '/banking-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingRoute = BankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banking': typeof BankingRoute
  '/banking-accounts': typeof BankingAccountsRoute
  '/black-card': typeof BlackCardRoute
  '/business-network': typeof BusinessNetworkRoute
  '/coin': typeof CoinRoute
  '/contact': typeof ContactRoute
  '/creators-calendar': typeof CreatorsCalendarRoute
  '/dashboard': typeof DashboardRoute
  '/dlt': typeof DltRoute
  '/exchange': typeof ExchangeRoute
  '/explorer': typeof ExplorerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/heed': typeof HeedRoute
  '/heritage-judah': typeof HeritageJudahRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/membership': typeof MembershipRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRoute
  '/property': typeof PropertyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/royal-priesthood': typeof RoyalPriesthoodRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-club': typeof SocialClubRoute
  '/tokens': typeof TokensRoute
  '/tps': typeof TpsRoute
  '/trading-hub': typeof TradingHubRoute
  '/universe-commerce': typeof UniverseCommerceRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banking': typeof BankingRoute
  '/banking-accounts': typeof BankingAccountsRoute
  '/black-card': typeof BlackCardRoute
  '/business-network': typeof BusinessNetworkRoute
  '/coin': typeof CoinRoute
  '/contact': typeof ContactRoute
  '/creators-calendar': typeof CreatorsCalendarRoute
  '/dashboard': typeof DashboardRoute
  '/dlt': typeof DltRoute
  '/exchange': typeof ExchangeRoute
  '/explorer': typeof ExplorerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/heed': typeof HeedRoute
  '/heritage-judah': typeof HeritageJudahRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/membership': typeof MembershipRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRoute
  '/property': typeof PropertyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/royal-priesthood': typeof RoyalPriesthoodRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-club': typeof SocialClubRoute
  '/tokens': typeof TokensRoute
  '/tps': typeof TpsRoute
  '/trading-hub': typeof TradingHubRoute
  '/universe-commerce': typeof UniverseCommerceRoute
  '/vision': typeof VisionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/banking': typeof BankingRoute
  '/banking-accounts': typeof BankingAccountsRoute
  '/black-card': typeof BlackCardRoute
  '/business-network': typeof BusinessNetworkRoute
  '/coin': typeof CoinRoute
  '/contact': typeof ContactRoute
  '/creators-calendar': typeof CreatorsCalendarRoute
  '/dashboard': typeof DashboardRoute
  '/dlt': typeof DltRoute
  '/exchange': typeof ExchangeRoute
  '/explorer': typeof ExplorerRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/heed': typeof HeedRoute
  '/heritage-judah': typeof HeritageJudahRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/membership': typeof MembershipRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRoute
  '/property': typeof PropertyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/royal-priesthood': typeof RoyalPriesthoodRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-club': typeof SocialClubRoute
  '/tokens': typeof TokensRoute
  '/tps': typeof TpsRoute
  '/trading-hub': typeof TradingHubRoute
  '/universe-commerce': typeof UniverseCommerceRoute
  '/vision': typeof VisionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/banking'
    | '/banking-accounts'
    | '/black-card'
    | '/business-network'
    | '/coin'
    | '/contact'
    | '/creators-calendar'
    | '/dashboard'
    | '/dlt'
    | '/exchange'
    | '/explorer'
    | '/forgot-password'
    | '/heed'
    | '/heritage-judah'
    | '/login'
    | '/marketplace'
    | '/membership'
    | '/profile'
    | '/properties'
    | '/property'
    | '/register'
    | '/reset-password'
    | '/royal-priesthood'
    | '/sitemap.xml'
    | '/social-club'
    | '/tokens'
    | '/tps'
    | '/trading-hub'
    | '/universe-commerce'
    | '/vision'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/banking'
    | '/banking-accounts'
    | '/black-card'
    | '/business-network'
    | '/coin'
    | '/contact'
    | '/creators-calendar'
    | '/dashboard'
    | '/dlt'
    | '/exchange'
    | '/explorer'
    | '/forgot-password'
    | '/heed'
    | '/heritage-judah'
    | '/login'
    | '/marketplace'
    | '/membership'
    | '/profile'
    | '/properties'
    | '/property'
    | '/register'
    | '/reset-password'
    | '/royal-priesthood'
    | '/sitemap.xml'
    | '/social-club'
    | '/tokens'
    | '/tps'
    | '/trading-hub'
    | '/universe-commerce'
    | '/vision'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/banking'
    | '/banking-accounts'
    | '/black-card'
    | '/business-network'
    | '/coin'
    | '/contact'
    | '/creators-calendar'
    | '/dashboard'
    | '/dlt'
    | '/exchange'
    | '/explorer'
    | '/forgot-password'
    | '/heed'
    | '/heritage-judah'
    | '/login'
    | '/marketplace'
    | '/membership'
    | '/profile'
    | '/properties'
    | '/property'
    | '/register'
    | '/reset-password'
    | '/royal-priesthood'
    | '/sitemap.xml'
    | '/social-club'
    | '/tokens'
    | '/tps'
    | '/trading-hub'
    | '/universe-commerce'
    | '/vision'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BankingRoute: typeof BankingRoute
  BankingAccountsRoute: typeof BankingAccountsRoute
  BlackCardRoute: typeof BlackCardRoute
  BusinessNetworkRoute: typeof BusinessNetworkRoute
  CoinRoute: typeof CoinRoute
  ContactRoute: typeof ContactRoute
  CreatorsCalendarRoute: typeof CreatorsCalendarRoute
  DashboardRoute: typeof DashboardRoute
  DltRoute: typeof DltRoute
  ExchangeRoute: typeof ExchangeRoute
  ExplorerRoute: typeof ExplorerRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HeedRoute: typeof HeedRoute
  HeritageJudahRoute: typeof HeritageJudahRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  MembershipRoute: typeof MembershipRoute
  ProfileRoute: typeof ProfileRoute
  PropertiesRoute: typeof PropertiesRoute
  PropertyRoute: typeof PropertyRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoyalPriesthoodRoute: typeof RoyalPriesthoodRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialClubRoute: typeof SocialClubRoute
  TokensRoute: typeof TokensRoute
  TpsRoute: typeof TpsRoute
  TradingHubRoute: typeof TradingHubRoute
  UniverseCommerceRoute: typeof UniverseCommerceRoute
  VisionRoute: typeof VisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe-commerce': {
      id: '/universe-commerce'
      path: '/universe-commerce'
      fullPath: '/universe-commerce'
      preLoaderRoute: typeof UniverseCommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading-hub': {
      id: '/trading-hub'
      path: '/trading-hub'
      fullPath: '/trading-hub'
      preLoaderRoute: typeof TradingHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tps': {
      id: '/tps'
      path: '/tps'
      fullPath: '/tps'
      preLoaderRoute: typeof TpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-club': {
      id: '/social-club'
      path: '/social-club'
      fullPath: '/social-club'
      preLoaderRoute: typeof SocialClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/royal-priesthood': {
      id: '/royal-priesthood'
      path: '/royal-priesthood'
      fullPath: '/royal-priesthood'
      preLoaderRoute: typeof RoyalPriesthoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property': {
      id: '/property'
      path: '/property'
      fullPath: '/property'
      preLoaderRoute: typeof PropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage-judah': {
      id: '/heritage-judah'
      path: '/heritage-judah'
      fullPath: '/heritage-judah'
      preLoaderRoute: typeof HeritageJudahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heed': {
      id: '/heed'
      path: '/heed'
      fullPath: '/heed'
      preLoaderRoute: typeof HeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dlt': {
      id: '/dlt'
      path: '/dlt'
      fullPath: '/dlt'
      preLoaderRoute: typeof DltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creators-calendar': {
      id: '/creators-calendar'
      path: '/creators-calendar'
      fullPath: '/creators-calendar'
      preLoaderRoute: typeof CreatorsCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coin': {
      id: '/coin'
      path: '/coin'
      fullPath: '/coin'
      preLoaderRoute: typeof CoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-network': {
      id: '/business-network'
      path: '/business-network'
      fullPath: '/business-network'
      preLoaderRoute: typeof BusinessNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/black-card': {
      id: '/black-card'
      path: '/black-card'
      fullPath: '/black-card'
      preLoaderRoute: typeof BlackCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking-accounts': {
      id: '/banking-accounts'
      path: '/banking-accounts'
      fullPath: '/banking-accounts'
      preLoaderRoute: typeof BankingAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking': {
      id: '/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof BankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BankingRoute: BankingRoute,
  BankingAccountsRoute: BankingAccountsRoute,
  BlackCardRoute: BlackCardRoute,
  BusinessNetworkRoute: BusinessNetworkRoute,
  CoinRoute: CoinRoute,
  ContactRoute: ContactRoute,
  CreatorsCalendarRoute: CreatorsCalendarRoute,
  DashboardRoute: DashboardRoute,
  DltRoute: DltRoute,
  ExchangeRoute: ExchangeRoute,
  ExplorerRoute: ExplorerRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HeedRoute: HeedRoute,
  HeritageJudahRoute: HeritageJudahRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  MembershipRoute: MembershipRoute,
  ProfileRoute: ProfileRoute,
  PropertiesRoute: PropertiesRoute,
  PropertyRoute: PropertyRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoyalPriesthoodRoute: RoyalPriesthoodRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialClubRoute: SocialClubRoute,
  TokensRoute: TokensRoute,
  TpsRoute: TpsRoute,
  TradingHubRoute: TradingHubRoute,
  UniverseCommerceRoute: UniverseCommerceRoute,
  VisionRoute: VisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
